testName: mohit-test23
testPlan: AppServiceLoadTest.jmx
description: ''
engineInstances: 1
splitAllCSVs: False
# secrets:
#   - name: my-secret
#     value: https://usermi-test-kv.vault-int.azure-int.net/secrets/secret-test/12ad09faba37415083872658804e5acd
failureCriteria:
  - percentage(error) > 1
  # - min(response_time_ms) > 100
  # - Provider: percentage(error) > 1
  # - Provider: min(response_time_ms) > 100
  # - Provider: p90(response_time_ms) > 100
properties:
  - userPropertyFile: "peak-load.properties"