displayName: blob_to_array_ado3
testPlan: SampleApp.jmx
description: ''
engineInstances: 1
testId: mohit-test-gh-csv-test
splitAllCSVs: False
configurationFiles:
- ..\CloudNativeTest-AutomationTask\inputartifacts.zip
- ../CloudNativeTest-AutomationTask/testcsvfile.csv
failureCriteria: []
