name: pr build check

on:
  push:
    branches:
      - releases/*
      
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - releases/*

env:
  LOAD_TEST_RESOURCE: "rbac-test"
  LOAD_TEST_RESOURCE_GROUP: "radhika-test"
  COMMIT_ID : ${{ github.sha }}

jobs:
  run-integration-test:
    environment: automation test
    name: Validate PR
    strategy:
      matrix:
        os: [windows-latest]
        configFile: ['sample-test-url.yaml', 'sample-test-jmx.yaml'] 
        
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - uses: actions/checkout@v2
      name: Checkout from PR branch
      with: 
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        path: 'load-testing'
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Installing dependencies and building latest changes
      run: |
        cd load-testing
        npm install --include=dev -f
        npm ci

    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: 'Azure Load Testing'
      uses: ./load-testing
      with:
        loadTestConfigFile: ${{ matrix.configFile }}
        loadTestResource: ${{ env.LOAD_TEST_RESOURCE }}
        resourceGroup: ${{ env.LOAD_TEST_RESOURCE_GROUP }}
      