name: pr build check

on:
  push:
    branches:
      - releases/*
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - releases/*
      - main

# NOTE : This workflow doesn't run on PRs against forks of this repositories
# Since they won't have access to the repository secrets. Ref: https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_CREDENTIALS
#
# 2. Change these variables for your configuration:

env:
  LOAD_TEST_RESOURCE: "rbac-test"
  LOAD_TEST_RESOURCE_GROUP: "radhika-test"
  COMMIT_ID : ${{ github.sha }}

jobs:
  run-integration-test:
    environment: automation test
    name: Validate PR
    strategy:
      matrix:
        os: [windows-latest]
        configFile: ['sample-test-url.yaml', 'sample-test-jmx.yaml'] 
        
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Installing dependencies and building latest changes
      run: |
        npm install --include=dev -f
        npm ci

    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
  
    - name: 'Azure Load Testing'
      uses: ./
      with:
        loadTestConfigFile: ${{ matrix.configFile }}
        loadTestResource: ${{ env.LOAD_TEST_RESOURCE }}
        resourceGroup: ${{ env.LOAD_TEST_RESOURCE_GROUP }}
      